name: Maven Build and Test for GitHub Classroom

# Trigger the workflow on push or pull requests to any branch
on: 
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Java (you can specify any required version here, like Java 11 or Java 17)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'

      # Cache Maven dependencies to speed up build times
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Install Maven dependencies
      - name: Install Maven dependencies
        run: mvn install -DskipTests -Dgpg.skip=true
        working-directory: MatrixAssignment

      # Run Maven tests
      - name: Run Maven tests
        run: mvn test -Dgpg.skip=true
        working-directory: MatrixAssignment


      # # Optionally, upload test results
      # - name: Archive test results
      #   if: always()
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: test-results
      #     path: target/surefire-reports/
